// INTERRUPT  TIMER ACTIVITY ( PERIODIC  TIMER)
#include<stdint.h>
#include"tm4c123gh6pm.h"
intmain(void)
{
	SYSCTL_RCC_R |= 0X024003C0;
	SYSCTL_RCGCGPIO_R |= SYSCTL_RCGCGPIO_R5;
	GPIO_PORTF_DEN_R |= 0X0F;
	GPIO_PORTF_DIR_R |= 0X0F;
	SYSCTL_RCGCTIMER_R |= SYSCTL_RCGCTIMER_R0;
	TIMER0_CTL_R &= ~TIMER_CTL_TAEN;
	TIMER0_CFG_R |= TIMER_CFG_32_BIT_TIMER;
	TIMER0_TAMR_R |= TIMER_TAMR_TAMR_PERIOD;
	TIMER0_TAILR_R = 1600000;
	NVIC_EN0_R |= 0X00080000;
	TIMER0_IMR_R |= TIMER_IMR_TATOIM;
	TIMER0_CTL_R |= TIMER_CTL_TAEN;
	while (1)
	{

	}
}
voidTIMER0INTHANDLER(void)
{
	TIMER0_ICR_R = 0X00000001;
	GPIO_PORTF_DATA_R ^= 0X02;
}
